#Config for bench-test
service:
  env: "development"
  deployment: "test"
  role: "all"
  domain: "chronos-bench"
  serverHostPort: ["127.0.0.1:7933"]
  httpListenPort: 9696

worker:
  numTaskLists: 2

basic:
  totalLaunchCount: 100
  routineCount: 1
  chainSequence: 4
  concurrentCount: 1
  payloadSizeBytes: 1024

load:
  testName: "chronos_marketplace_10"
  workflowRPS: 100
  numTaskLists: 2

zap:
  level: info
  outputPaths: ["stdout"]
  errorOutputPaths: ["stdout"]

statsd:
  addr: 127.0.0.1:8125
  prefix: cadence-bench
